
-- Drop Constraint, Rename and Create Table SQL

CREATE TABLE GIM.BROKER
(
    BROKER_ID decimal  NOT NULL,
    OFFICE_LOCATION_ID decimal,
    BROKER_LAST_NAME string  NOT NULL,
    BROKER_FIRST_NAME string  NOT NULL,
    BROKER_MIDDLE_INITIAL string,
    MANAGER_ID decimal,
    YEARS_WITH_FIRM decimal(4,0)  NOT NULL
)

;
CREATE TABLE GIMDW.BROKER_DIM
(
    BROKER_ID decimal  NOT NULL,
    BROKER_NAME string  NOT NULL,
    YEARS_WITH_FIRM decimal(4,0)  NOT NULL
)

;
CREATE TABLE GIM.CLIENT
(
    CLIENT_ID decimal  NOT NULL,
    CLIENT_FIRST_NAME string  NOT NULL,
    CLIENT_LAST_NAME string  NOT NULL,
    CLIENT_GENDER string  NOT NULL,
    CLIENT_YEAR_OF_BIRTH decimal(4,0)  NOT NULL,
    CLIENT_MARITAL_STATUS string,
    CLIENT_STREET_ADDRESS string  NOT NULL,
    CLIENT_POSTAL_CODE string  NOT NULL,
    CLIENT_CITY string  NOT NULL,
    CLIENT_STATE_PROVINCE string  NOT NULL,
    CLIENT_PHONE_NUMBER string  NOT NULL,
    CLIENT_HOUSEHOLD_INCOME decimal(30,2),
    CLIENT_COUNTRY string,
    BROKER_ID decimal  NOT NULL
)

;
CREATE TABLE GIMDW.CLIENT_FACT
(
    CLIENT_ID decimal  NOT NULL,
    INVESTMENT_ID decimal  NOT NULL,
    BROKER_ID decimal  NOT NULL,
    REGION_ID decimal  NOT NULL,
    CLIENT_FIRST_NAME string  NOT NULL,
    CLIENT_LAST_NAME string  NOT NULL,
    CLIENT_GENDER string  NOT NULL,
    CLIENT_YEAR_OF_BIRTH decimal(4,0)  NOT NULL,
    CLIENT_MARITAL_STATUS string,
    CLIENT_STREET_ADDRESS string  NOT NULL,
    CLIENT_POSTAL_CODE string  NOT NULL,
    CLIENT_CITY string  NOT NULL,
    CLIENT_STATE_PROVINCE string  NOT NULL,
    CLIENT_PHONE_NUMBER string  NOT NULL,
    CLIENT_HOUSEHOLD_INCOME decimal(30,2),
    CLIENT_COUNTRY string,
    ACTION string  NOT NULL,
    PRICE decimal(12,2)  NOT NULL,
    NUMBER_OF_UNITS decimal  NOT NULL,
    TRANSACTION_STATUS string  NOT NULL,
    TRANSACTION_SUB_TIMESTAMP date  NOT NULL,
    TRANSACTION_COMP_TIMESTAMP date  NOT NULL,
    DESCRIPTION string,
    BROKER_COMMISSION decimal(30,2)
)

;
CREATE TABLE GIM.CLIENT_TRANSACTION
(
    CLIENT_TRANSACTION_ID decimal  NOT NULL,
    CLIENT_ID decimal  NOT NULL,
    INVESTMENT_ID decimal  NOT NULL,
    ACTION string  NOT NULL,
    PRICE decimal(12,2)  NOT NULL,
    NUMBER_OF_UNITS decimal  NOT NULL,
    TRANSACTION_STATUS string  NOT NULL,
    TRANSACTION_SUB_TIMESTAMP date  NOT NULL,
    TRANSACTION_COMP_TIMESTAMP date  NOT NULL,
    DESCRIPTION string,
    BROKER_ID decimal,
    BROKER_COMMISSION decimal(30,2)
)

;
CREATE TABLE GIM.INVESTMENT
(
    INVESTMENT_ID decimal  NOT NULL,
    INVESTMENT_TYPE_ID decimal,
    INVESTMENT_VENDOR string  NOT NULL,
    INVESTMENT_NAME string,
    INVESTMENT_UNIT string,
    INVESTMENT_DURATION string
)

;
CREATE TABLE GIMDW.INVESTMENT_DIM
(
    INVESTMENT_ID decimal  NOT NULL,
    INVESTMENT_VENDOR string  NOT NULL,
    INVESTMENT_NAME string,
    INVESTMENT_UNIT string,
    INVESTMENT_DURATION string
)

;
CREATE TABLE GIM.INVESTMENT_TYPE
(
    INVESTMENT_TYPE_ID decimal  NOT NULL,
    INVESTMENT_TYPE_NAME string  NOT NULL
)

;
CREATE TABLE GIM.OFFICE_LOCATION
(
    OFFICE_LOCATION_ID decimal  NOT NULL,
    OFFICE_NAME string  NOT NULL,
    OFFICE_ADDRESS string  NOT NULL,
    OFFICE_CITY string  NOT NULL,
    OFFICE_STATE_PROVINCE string  NOT NULL,
    OFFICE_POSTAL_CODE string  NOT NULL,
    OFFICE_COUNTRY string
)

;
CREATE TABLE GIMDW.REGIONAL_DIM
(
    REGION_ID decimal  NOT NULL,
    STATE_CODE string,
    ZIP_CODE string,
    DEMOGRAPHIC_CODE string,
    CITY string
)

;

-- Add Constraint SQL


ALTER TABLE GIM.BROKER
    ADD CONSTRAINT broker_pk PRIMARY KEY (BROKER_ID) 

;

ALTER TABLE GIMDW.BROKER_DIM
    ADD CONSTRAINT broker_pk PRIMARY KEY (BROKER_ID) 

;

ALTER TABLE GIM.CLIENT
    ADD CONSTRAINT client_pk PRIMARY KEY (CLIENT_ID) 

;

ALTER TABLE GIMDW.CLIENT_FACT
    ADD CONSTRAINT client_pk PRIMARY KEY (CLIENT_ID, INVESTMENT_ID, BROKER_ID, REGION_ID) 

;

ALTER TABLE GIM.CLIENT_TRANSACTION
    ADD CONSTRAINT client_transaction_pk PRIMARY KEY (CLIENT_TRANSACTION_ID) 

;

ALTER TABLE GIM.INVESTMENT
    ADD CONSTRAINT investment_pk PRIMARY KEY (INVESTMENT_ID) 

;

ALTER TABLE GIMDW.INVESTMENT_DIM
    ADD CONSTRAINT investment_pk PRIMARY KEY (INVESTMENT_ID) 

;

ALTER TABLE GIM.INVESTMENT_TYPE
    ADD CONSTRAINT investment_type_pk PRIMARY KEY (INVESTMENT_TYPE_ID) 

;

ALTER TABLE GIM.OFFICE_LOCATION
    ADD CONSTRAINT office_location_pk PRIMARY KEY (OFFICE_LOCATION_ID) 

;

ALTER TABLE GIMDW.REGIONAL_DIM
    ADD CONSTRAINT pk32 PRIMARY KEY (REGION_ID) 

;

-- Alter Index SQL


CREATE BLOOMFILTER INDEX ON TABLE GIM.BROKER
FOR COLUMNS (OFFICE_LOCATION_ID)


;

CREATE BLOOMFILTER INDEX ON TABLE GIM.CLIENT
FOR COLUMNS (BROKER_ID)


;

CREATE BLOOMFILTER INDEX ON TABLE GIMDW.CLIENT_FACT
FOR COLUMNS (INVESTMENT_ID)


;

CREATE BLOOMFILTER INDEX ON TABLE GIM.CLIENT_TRANSACTION
FOR COLUMNS (CLIENT_ID)


;

CREATE BLOOMFILTER INDEX ON TABLE GIM.INVESTMENT
FOR COLUMNS (INVESTMENT_TYPE_ID)


;

-- Add Referencing Foreign Keys SQL


ALTER TABLE GIM.BROKER
    ADD CONSTRAINT BROKER_MANAGER
    FOREIGN KEY (MANAGER_ID)
    REFERENCES GIM.BROKER (BROKER_ID)

;

ALTER TABLE GIM.CLIENT
    ADD CONSTRAINT CLIENT_BROKER
    FOREIGN KEY (BROKER_ID)
    REFERENCES GIM.BROKER (BROKER_ID)

;

ALTER TABLE GIM.CLIENT_TRANSACTION
    ADD CONSTRAINT CLIENT_TRANSACTION_BROKER
    FOREIGN KEY (BROKER_ID)
    REFERENCES GIM.BROKER (BROKER_ID)

;

ALTER TABLE GIM.BROKER
    ADD CONSTRAINT BROKER_OFFICE_LOCATION
    FOREIGN KEY (OFFICE_LOCATION_ID)
    REFERENCES GIM.OFFICE_LOCATION (OFFICE_LOCATION_ID)

;

ALTER TABLE GIMDW.CLIENT_FACT
    ADD CONSTRAINT CLIENT_BROKER
    FOREIGN KEY (BROKER_ID)
    REFERENCES GIMDW.BROKER_DIM (BROKER_ID)

;

ALTER TABLE GIM.CLIENT_TRANSACTION
    ADD CONSTRAINT CLIENT_TRANSACTION_CLIENT
    FOREIGN KEY (CLIENT_ID)
    REFERENCES GIM.CLIENT (CLIENT_ID)

;

ALTER TABLE GIMDW.CLIENT_FACT
    ADD 
    FOREIGN KEY (REGION_ID)
    REFERENCES GIMDW.REGIONAL_DIM (REGION_ID)

;

ALTER TABLE GIMDW.CLIENT_FACT
    ADD CONSTRAINT CLIENT_TRANSACTION_INVESTMENT
    FOREIGN KEY (INVESTMENT_ID)
    REFERENCES GIMDW.INVESTMENT_DIM (INVESTMENT_ID)

;

ALTER TABLE GIM.CLIENT_TRANSACTION
    ADD CONSTRAINT CLIENT_TRANSACTION_INVESTMENT
    FOREIGN KEY (INVESTMENT_ID)
    REFERENCES GIM.INVESTMENT (INVESTMENT_ID)

;

ALTER TABLE GIM.INVESTMENT
    ADD CONSTRAINT INVESTMENT_TYPE
    FOREIGN KEY (INVESTMENT_TYPE_ID)
    REFERENCES GIM.INVESTMENT_TYPE (INVESTMENT_TYPE_ID)

;

-- Add Comments SQL


COMMENT ON TABLE GIM.BROKER IS 'Broker contains all the investment advisors/brokers that work at the company.'

;

COMMENT ON TABLE GIMDW.BROKER_DIM IS 'Broker contains all the investment advisors/brokers that work at the company.'

;

COMMENT ON TABLE GIM.CLIENT IS 'Client contains all the customers who have investments being managed by the compay.'

;

COMMENT ON TABLE GIMDW.CLIENT_FACT IS 'Client contains all the customers who have investments being managed by the compay.'

;

COMMENT ON TABLE GIM.CLIENT_TRANSACTION IS 'Client transaction contains information regarding every buy or sell transaction that a client makes through the company.'

;

COMMENT ON TABLE GIM.INVESTMENT IS 'Investment contains all the different investments currently offered to customers through the company.'

;

COMMENT ON TABLE GIMDW.INVESTMENT_DIM IS 'Investment contains all the different investments currently offered to customers through the company.'

;

COMMENT ON TABLE GIM.INVESTMENT_TYPE IS 'Investment type contains all the different types/categories of investments offered to clients by the company.'

;

COMMENT ON TABLE GIM.OFFICE_LOCATION IS 'Office location contains information regarding the worldwide office locations of the company.'

;
