
-- Drop Constraint, Rename and Create Table SQL

CREATE TABLE ANIL.Entity1
(
    PKAttribute1 CHAR(10) NOT NULL
)
;
ALTER TABLE ANIL.Entity1 DATA CAPTURE NONE
;
ALTER TABLE ANIL.Entity1 NOT VOLATILE
;
ALTER TABLE ANIL.Entity1 LOCKSIZE ROW
;
CREATE UNIQUE INDEX ANIL.PK1
    ON ANIL.Entity1(PKAttribute1)
;
ALTER TABLE ANIL.Entity1 ADD CONSTRAINT PK1
PRIMARY KEY (PKAttribute1)
;
CREATE TABLE ANIL.Entity2
(
    PKAttribute1 CHAR(10) NOT NULL
)
;
ALTER TABLE ANIL.Entity2 DATA CAPTURE NONE
;
ALTER TABLE ANIL.Entity2 NOT VOLATILE
;
ALTER TABLE ANIL.Entity2 LOCKSIZE ROW
;
CREATE UNIQUE INDEX ANIL.PK2
    ON ANIL.Entity2(PKAttribute1)
;
ALTER TABLE ANIL.Entity2 ADD CONSTRAINT PK2
PRIMARY KEY (PKAttribute1)
;
CREATE TABLE ANIL.Entity3
(
    PKAttribute1 CHAR(10) NOT NULL
)
;
ALTER TABLE ANIL.Entity3 DATA CAPTURE NONE
;
ALTER TABLE ANIL.Entity3 NOT VOLATILE
;
ALTER TABLE ANIL.Entity3 LOCKSIZE ROW
;
CREATE UNIQUE INDEX ANIL.PK3
    ON ANIL.Entity3(PKAttribute1)
;
ALTER TABLE ANIL.Entity3 ADD CONSTRAINT PK3
PRIMARY KEY (PKAttribute1)
;
CREATE TABLE ANIL.Entity4
(
    PKAttribute1 CHAR(10) NOT NULL
)
;
ALTER TABLE ANIL.Entity4 DATA CAPTURE NONE
;
ALTER TABLE ANIL.Entity4 NOT VOLATILE
;
ALTER TABLE ANIL.Entity4 LOCKSIZE ROW
;
CREATE UNIQUE INDEX ANIL.PK4
    ON ANIL.Entity4(PKAttribute1)
;
ALTER TABLE ANIL.Entity4 ADD CONSTRAINT PK4
PRIMARY KEY (PKAttribute1)
;
CREATE TABLE ANIL.Entity5
(
    PKAttribute1 CHAR(10) NOT NULL
)
;
ALTER TABLE ANIL.Entity5 DATA CAPTURE NONE
;
ALTER TABLE ANIL.Entity5 NOT VOLATILE
;
ALTER TABLE ANIL.Entity5 LOCKSIZE ROW
;
CREATE UNIQUE INDEX ANIL.PK5
    ON ANIL.Entity5(PKAttribute1)
;
ALTER TABLE ANIL.Entity5 ADD CONSTRAINT PK5
PRIMARY KEY (PKAttribute1)
;
CREATE TABLE ANIL.Entity6
(
    PKAttribute1 CHAR(10) NOT NULL
)
;
ALTER TABLE ANIL.Entity6 DATA CAPTURE NONE
;
ALTER TABLE ANIL.Entity6 NOT VOLATILE
;
ALTER TABLE ANIL.Entity6 LOCKSIZE ROW
;
CREATE UNIQUE INDEX ANIL.PK6
    ON ANIL.Entity6(PKAttribute1)
;
ALTER TABLE ANIL.Entity6 ADD CONSTRAINT PK6
PRIMARY KEY (PKAttribute1)
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE ANIL.Entity2 
    ADD 
FOREIGN KEY (PKAttribute1)
REFERENCES ANIL.Entity6 (PKAttribute1)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;
ALTER TABLE ANIL.Entity3 
    ADD 
FOREIGN KEY (PKAttribute1)
REFERENCES ANIL.Entity5 (PKAttribute1)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;
ALTER TABLE ANIL.Entity4 
    ADD 
FOREIGN KEY (PKAttribute1)
REFERENCES ANIL.Entity2 (PKAttribute1)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;
ALTER TABLE ANIL.Entity5 
    ADD 
FOREIGN KEY (PKAttribute1)
REFERENCES ANIL.Entity1 (PKAttribute1)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;
ALTER TABLE ANIL.Entity6 
    ADD 
FOREIGN KEY (PKAttribute1)
REFERENCES ANIL.Entity3 (PKAttribute1)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;
